version: "2"
plugins:
  rubocop:
    enabled: true
    channel: "rubocop-0-59-2" # need to keep this value the same as rubocop version
                            # https://docs.codeclimate.com/v1.0/docs/rubocop#section-using-rubocop-s-newer-versions
exclude_patterns:
  - "**/bin/"
  - "config/"
  - "db/"
  - "**/tmp/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "public/"
